# Generated by Django 6.0.5 on 2026-05-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_medicalhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
